# Generated by Django 5.1.4 on 2025-03-18 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_bio_photo_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
